{"uuid": "c4b42daf-1657-4c9b-b7b7-1862105815de", "children": ["ed3f7698-1812-4ca1-a656-369d8852f077", "f8cde757-00b1-45a1-9059-c26c86438372"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device.\n\n", "trace": "  File \"f:\\python3.6\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"f:\\python3.6\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"f:\\python3.6\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"f:\\python3.6\\lib\\site-packages\\_pytest\\unittest.py\", line 131, in fixture\n    setup()\n  File \"F:\\黑马\\黑马就业班\\UI自动化测试\\课堂练习\\day11\\HM_TT_UI_TEST\\case\\app\\test_query_article.py\", line 12, in setUpClass\n    cls.driver = DriverUtils.get_app_driver()\n  File \"F:\\黑马\\黑马就业班\\UI自动化测试\\课堂练习\\day11\\HM_TT_UI_TEST\\utils.py\", line 95, in get_app_driver\n    cls.__app_driver = appium.webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)\n  File \"f:\\python3.6\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 155, in __init__\n    proxy\n  File \"f:\\python3.6\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"f:\\python3.6\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"f:\\python3.6\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"f:\\python3.6\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1598577216567, "stop": 1598577262905}], "start": 1598577216566, "stop": 1598577263175}